# Generated by Django 4.2 on 2025-06-19 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_resolved',
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('user', 'User'), ('post', 'Post')], max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_on_post', to='posts.post'),
        ),
    ]
