# Generated by Django 4.2 on 2025-06-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_timestamp_report_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
