# Generated by Django 4.2 on 2025-01-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_report_resolved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
