# Generated by Django 4.2 on 2025-08-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username_lower',
            field=models.CharField(db_index=True, default='', editable=False, max_length=150),
        ),
    ]
