"""
Django settings for kefi_beta_version1 project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',')

# Application definition

INSTALLED_APPS = [
    'users.apps.UsersConfig',  # use AppConfig for signals
    'posts',
    'notifications.apps.NotificationsConfig',  # use AppConfig for signals
    'core',
    'channels',
    'dm',  # renamed from messages
    'sm_app',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',  # <-- Add this line
    'webpush',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # <-- Add this line
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kefi_beta_version1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # add global templates dir
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.unread_notifications_count',
                'dm.context_processors.unread_dm_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'kefi_beta_version1.wsgi.application'

ASGI_APPLICATION = 'kefi_beta_version1.asgi.application'

APPEND_SLASH = False 


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'taken_db',
#         'USER': 'root',      
#         'PASSWORD': '',     
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }

# Database configuration
if os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true':
    # Development - Use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Production - Use Aiven MySQL
    ca_cert_path = os.path.join(BASE_DIR, 'ca.pem')
    ssl_options = {}
    
    if os.path.exists(ca_cert_path):
        ssl_options = {
            'ssl': {
                'ca': ca_cert_path,
            },
        }
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('MYSQL_DATABASE', 'defaultdb'),
            'USER': os.environ.get('MYSQL_USER', 'avnadmin'),
            'PASSWORD': os.environ.get('MYSQL_PASSWORD', ''),
            'HOST': os.environ.get('MYSQL_HOST', 'kefi-mysql-kefi-db.g.aivencloud.com'),
            'PORT': os.environ.get('MYSQL_PORT', '15747'),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES', NAMES 'utf8mb4'",
                **ssl_options,
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 6},  # Lowered minimum length
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Set timezone to Nigeria (WAT - West Africa Time, UTC+1)
TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'sm_app/static'),
    os.path.join(BASE_DIR, 'users/static'),
]

# WhiteNoise configuration
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True
WHITENOISE_MAX_AGE = 31536000  # 1 year cache


# Media files (user uploads) - Backblaze B2 via django-storages
import os

WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BHi9xARCd-PmsalLQqsxwFo6DMBXBeDSK7D-Yu-G-tKxnYQ0rIk4W-ImbZQk7hsyWSGDNGeBXhqx_Iw3PEA-N0o=",
    "VAPID_PRIVATE_KEY": "vl6ihd7UPjGSMrLCJ6LIDb9hQsawIslkZHbz5FFIg5E=",
    "VAPID_ADMIN_EMAIL": "misterhge@gmail.com"
}

INSTALLED_APPS += ['storages']

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

AWS_STORAGE_BUCKET_NAME = os.environ.get('B2_BUCKET_NAME')  # just the bucket name
AWS_S3_ENDPOINT_URL = f"https://s3.{os.environ.get('B2_REGION')}.backblazeb2.com"  # no bucket in URL
AWS_ACCESS_KEY_ID = os.environ.get('B2_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('B2_APP_KEY')
AWS_S3_ADDRESSING_STYLE = "path"
AWS_QUERYSTRING_AUTH = True  # For private buckets!
AWS_QUERYSTRING_EXPIRE = 600  # Signed URL valid for 10 minutes

# MEDIA_URL is not set for private B2 buckets; django-storages will generate signed URLs
# Public URL for B2 bucket (set this to your bucket's public base URL)
# Public URL for B2 bucket (set this to your bucket's public base URL)
B2_PUBLIC_URL = os.environ.get('B2_PUBLIC_URL', f'https://YOUR-B2-URL-HERE/file/{AWS_STORAGE_BUCKET_NAME}')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/users/login/'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('GMAIL_USER')
EMAIL_HOST_PASSWORD = os.environ.get('GMAIL_PASSWORD')
DEFAULT_FROM_EMAIL = f"Kefi <{os.environ.get('GMAIL_USER')}>"

# CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = [
    "https://kefi.onrender.com",
]
# Security settings - these will be automatically handled by your hosting platform
SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = None